#!/bin/sh 

echo "Diga algo: " 
read valor 

case "$valor" in 
*[0-9]*) 
echo "$valor es un número entero" 
;; 
*) 
echo "$valor no es numerico" 
;; 
esac 

if [ $valor -gt 0 ] && [ $valor -lt 13 ]; then
    echo "${valor} es un MES correcto."
else
    echo "${valor} es un mes incorrecto."
fi;

#end.